version: '3.7'
services:
  web-server:
    build:
      context: ./Nginx
      args:
        - HOST=${HOST}
        - REST_NAME=api
        - ES_NAME=elastic
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - nginx-conf:/etc/nginx/conf.d
      - cert:/etc/letsencrypt
      # - cert-www:/var/www/certbot

volumes:
  nginx-conf:
  # cert-www:
  cert:   