version: '3.7'
services:
  web-server:
    build:
      context: ./Nginx
      args:
        - HOST=${HOST}
        - REST_NAME=rest
        - ES_NAME=elastic
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    command: "nginx -g 'daemon off;'"